name: fastrucks2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'



dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2

  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.2
  google_fonts:
  google_nav_bar: ^5.0.6
  
  #Firebase Database
  firebase_storage: ^11.0.3
  cloud_firestore: ^4.0.3
  firebase_core: ^2.1.1
  firebase_auth: ^4.1.0

  camera:
  path_provider:
  path:

  file_picker: ^5.2.1
  
  
  flutter_map: ^3.0.0
  carousel_slider: ^4.1.1
  dots_indicator: ^2.1.0
  flutter_form_builder: ^7.7.0
  #dropdownfield: ^1.0.0
  device_info: ^2.0.3
  package_info: ^2.0.2
  platform: ^3.1.0
  bubble_bottom_bar: ^2.0.0
  flutter_svg: ^1.1.6
  google_maps: ^6.2.0
  location: ^4.4.0
  device_info_plus: ^8.0.0
  get: ^4.6.5
  package_info_plus: ^3.0.1
  google_sign_in: ^6.1.4
  http: ^0.13.5
  
  json_serializable: ^6.5.4
  json_annotation: ^4.7.0
  http_parser: ^4.0.2
  pedantic: ^1.11.1
  image_picker: ^0.8.6
  geocoding: ^2.0.5
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.20-nullsafety.5
  mpesa_flutter_plugin: ^1.6.1
  dropdown_button2: ^1.8.9
  intl: ^0.17.0
  cached_network_image: ^3.2.2
  geolocator: ^9.0.2
  awesome_snackbar_content: ^0.0.8
  flutter_local_notifications: ^12.0.4
  smooth_page_indicator: ^1.0.1
  
  introduction_screen: ^3.1.8
  shared_preferences: ^2.2.0
  
  
  
  
  


  


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.11
  build_runner: ^2.3.2

flutter_native_splash:
  color: "#fdca69"
  image: assets/truck.png
  android: true
  ios: true


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/truck.png
  - assets/driver.png
  - assets/map_style.txt
  - assets/MPESA.jpg
  - assets/supplier.png
  - assets/logistics.png
  - assets/loading.png

 


    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#fonts:
#  - family: Schyler
fonts:
    - asset: fonts/Montserrat-Medium.ttf
    - asset: fonts/Montserrat-Regular.ttf
         
#           style: italic
#     - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
