// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJGoT1w71h0pcK0jcX5o6NQg2OxQYKKmg',
    appId: '1:446742646174:web:61126b129234dfba581a8f',
    messagingSenderId: '446742646174',
    projectId: 'fastrucks1-230a1',
    authDomain: 'fastrucks1-230a1.firebaseapp.com',
    storageBucket: 'fastrucks1-230a1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaPqOe6-Fuex5XOvMOW5a3NruZlkXuIy0',
    appId: '1:446742646174:android:d85fd54a5ba912fc581a8f',
    messagingSenderId: '446742646174',
    projectId: 'fastrucks1-230a1',
    storageBucket: 'fastrucks1-230a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFpb-i_jkaGVPeVt4YnZcSX9fGX0m81O4',
    appId: '1:446742646174:ios:6ef21bb52e0dafa1581a8f',
    messagingSenderId: '446742646174',
    projectId: 'fastrucks1-230a1',
    storageBucket: 'fastrucks1-230a1.appspot.com',
    iosClientId: '446742646174-7pi1igrm9rps5glnkb6qute9e9uvikmj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fastrucks2',
  );
}
